name: Release Deployment

on: 
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      env: 
        ENCRYPT_CODE: ${{ secrets.ENCRYPT_CODE }}
        ENCRYPT_IV: ${{ secrets.ENCRYPT_IV }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        envs: ENCRYPT_CODE, ENCRYPT_IV
        script: cd Git/ArcLight && git pull && rm -rf secrets/encrypt.json && touch secrets/encrypt.json && printf '{"code":"%s", "iv":"%s"}' "$ENCRYPT_CODE" "$ENCRYPT_IV" > secrets/encrypt.json && yarn && rm -rf dist && yarn build && rm -rf dist/static/js/vendor.*.js.map